# Generated by Django 3.2.7 on 2021-09-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='price',
        ),
    ]
