# Generated by Django 3.2.7 on 2021-09-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_equipment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1203.5, max_digits=20),
            preserve_default=False,
        ),
    ]
