# Generated by Django 3.2.7 on 2021-09-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mobile",
            field=models.CharField(default=123456789, max_length=15),
            preserve_default=False,
        ),
    ]
