# Generated by Django 3.2.7 on 2021-09-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0002_profile_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mobile",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
