# Generated by Django 3.2.7 on 2021-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
