# Generated by Django 3.2.7 on 2021-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210905_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='patient.jpg', upload_to='patient_pics'),
        ),
    ]
