# Generated by Django 3.2.7 on 2021-09-06 12:54

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_alter_patient_aadhaar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="dob",
            field=models.DateField(
                validators=[patients.models.dob_validator],
                verbose_name="Date of Birth (DOB)",
            ),
        ),
    ]
