# Generated by Django 3.2.7 on 2021-09-06 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0006_alter_patient_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="archived_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="patient_archived_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="patient_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
