# Generated by Django 3.2.7 on 2021-09-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_auto_20210906_1946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(default="patient.jpg", upload_to="doctor_pics"),
        ),
    ]
