# Generated by Django 3.2.7 on 2021-09-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_doctor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(default="doctor.jpg", upload_to="doctor_pics"),
        ),
    ]
